INSERT INTO Pertenece VALUES
('0', '1', CONVERT(CURRENT_DATE(), CHAR(10))),
('1', '2', CONVERT(CURRENT_DATE(), CHAR(10))),
('2', '6', CONVERT(CURRENT_DATE(), CHAR(10))),
('3', '8', CONVERT(CURRENT_DATE(), CHAR(10))),
('4', '8', CONVERT(CURRENT_DATE(), CHAR(10)));
